name             'consul'
maintainer       'Jayaram Pradhan'
maintainer_email 'jayaramimca@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures Consul servers/agent'
version          '1.0.0'